[project]
authors = ["surfer12 <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "java-genai"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=25.0.1,<26"
